#!/bin/sh

dotfilesdir=`pwd`

link() { # filename
	cd
	ln -sfn "$dotfilesdir/$1" ".$1"
}

link "vimrc"
link "vim"
link "gitconfig"
link "gitconfig_local"
link "inputrc"
link "tmux.conf"
link "tmux-onedark.tmux"
link "ssh/config"
